apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: desafio-py
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: LoadBalancer