services:
  app:
    image: desafio-py:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://dev:dev@db:5432/dev
      - REDIS_URL=redis://redis:6379/0
    networks:
      - app_network
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    networks:
      - app_network
      
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge